"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Homes",
      [
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.  cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "2",
          Direccion: "Manizales,Caldas",
          Latitud: 22.1,
          Longitud: 33.1,
          Cant_Cuartos: "2",
          Caracteristicas_Extra: "Tiene sauna",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "100m2",
          Precio: "20000",
          Descripcion:
            "Esta es un apartamento ubicado en una zona residencial de manizales",
            Imagen: JSON.stringify(
              {
                id: "prueba",
                url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
              },
              {
                id: "prueba02",
                url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
              }
            ),
          Tiene_Garaje_Moto: "si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "100.000.000",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "3",
          Direccion: "Bogotá, Cundinamarca",
          Latitud: 22.1,
          Longitud: 33.1,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene piscina",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "200m2",
          Precio: "5000000",
          Descripcion:
            "Esta es una casa ubicada en una zona exclusiva de Bogotá",
            Imagen: JSON.stringify(
              {
                id: "prueba",
                url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
              },
              {
                id: "prueba02",
                url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
              }
            ),
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "500000000",
          AgentId: "3",
          TypehousingId: "1",
          TypetargetId: "3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "4",
          Direccion: "Medellín, Antioquia",
          Latitud: 22.1,
          Longitud: 33.1,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Tiene vista panorámica",
          Tiene_Servicios_Incluidos: "Sí",
          Area_Inmueble: "150m2",
          Precio: "3500000",
          Descripcion:
            "Este es un apartamento moderno con una vista espectacular de la ciudad",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Sí",
          Tiene_Patio: "No",
          Cant_Baños: "3",
          Precio_Venta: "700000000",
          AgentId: "1",
          TypehousingId: "2",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "2",
          Direccion: "Bogotá,Cundinamarca",
          Latitud: 4.6097,
          Longitud: -74.0817,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Piscina privada",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "150m2",
          Precio: "350000",
          Descripcion: "Amplia casa familiar en el corazón de Bogotá",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "3",
          Precio_Venta: "5000000",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "3",
          Direccion: "Medellín,Antioquia",
          Latitud: 6.2447,
          Longitud: -75.5748,
          Cant_Cuartos: "2",
          Caracteristicas_Extra: "Vista panorámica a la montaña",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "80m2",
          Precio: "180000",
          Descripcion: "Apartamento acogedor con vista a la ciudad",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "No",
          Cant_Baños: "1",
          Precio_Venta: "1500000",
          AgentId: "3",
          TypehousingId: "1",
          TypetargetId: "3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "4",
          Direccion: "Cali,Valle del Cauca",
          Latitud: 3.4516,
          Longitud: -76.532,
          Cant_Cuartos: "5",
          Caracteristicas_Extra: "Gimnasio y sauna",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "200m2",
          Precio: "500000",
          Descripcion: "Casa moderna con comodidades de lujo en Cali",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "4",
          Precio_Venta: "8000000",
          AgentId: "1",
          TypehousingId: "3",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "5",
          Direccion: "Cartagena,Bolívar",
          Latitud: 10.391,
          Longitud: -75.4794,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Cerca de la playa",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "120m2",
          Precio: "300000",
          Descripcion:
            "Casa de estilo colonial en el centro histórico de Cartagena",
            Imagen: JSON.stringify(
              {
                id: "prueba",
                url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
              },
              {
                id: "prueba02",
                url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
              }
            ),
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2500000",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "6",
          Direccion: "Pereira,Risaralda",
          Latitud: 4.8136,
          Longitud: -75.6961,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Jardín amplio",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "180m2",
          Precio: "400000",
          Descripcion: "Chalet elegante con vistas a las montañas en Pereira",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "3",
          Precio_Venta: "6000000",
          AgentId: "3",
          TypehousingId: "3",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "7",
          Direccion: "Barranquilla,Atlántico",
          Latitud: 10.9639,
          Longitud: -74.7967,
          Cant_Cuartos: "2",
          Caracteristicas_Extra: "Vista al mar",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "100m2",
          Precio: "250000",
          Descripcion: "Apartamento moderno con balcón en Barranquilla",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "1800000",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "8",
          Direccion: "Santa Marta,Magdalena",
          Latitud: 11.2404,
          Longitud: -74.2115,
          Cant_Cuartos: "5",
          Caracteristicas_Extra: "Piscina comunitaria",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "200m2",
          Precio: "500000",
          Descripcion: "Casa de playa con acceso directo al mar en Santa Marta",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "4",
          Precio_Venta: "7000000",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "9",
          Direccion: "Villavicencio,Meta",
          Latitud: 4.142,
          Longitud: -73.6266,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Cerca de parques naturales",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "120m2",
          Precio: "280000",
          Descripcion: "Casa acogedora con jardín en Villavicencio",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2400000",
          AgentId: "3",
          TypehousingId: "3",
          TypetargetId: "3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "10",
          Direccion: "Cúcuta,Norte de Santander",
          Latitud: 7.8947,
          Longitud: -72.496,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Zona tranquila",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "150m2",
          Precio: "380000",
          Descripcion: "Amplia casa familiar en Cúcuta",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "No",
          Cant_Baños: "3",
          Precio_Venta: "3000000",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "10",
          Direccion: "Cúcuta,Norte de Santander",
          Latitud: 7.8947,
          Longitud: -72.496,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Zona tranquila",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "150m2",
          Precio: "380000",
          Descripcion: "Amplia casa familiar en Cúcuta",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "No",
          Cant_Baños: "3",
          Precio_Venta: "3000000",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "11",
          Direccion: "Pasto,Nariño",
          Latitud: 1.2136,
          Longitud: -77.2811,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Vista a la montaña",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "110m2",
          Precio: "250000",
          Descripcion: "Apartamento con encanto en el centro de Pasto",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "11",
          Direccion: "Pasto,Nariño",
          Latitud: 1.2136,
          Longitud: -77.2811,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Vista a la montaña",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "110m2",
          Precio: "250000",
          Descripcion: "Apartamento con encanto en el centro de Pasto",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "13",
          Direccion: "Armenia,Quindío",
          Latitud: 4.5341,
          Longitud: -75.6759,
          Cant_Cuartos: "2",
          Caracteristicas_Extra: "Casa de diseño contemporáneo",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "90m2",
          Precio: "200000",
          Descripcion: "Acogedora casa en el corazón de Armenia",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "1",
          Precio_Venta: "1800000",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "14",
          Direccion: "Manizales,Caldas",
          Latitud: 5.0586,
          Longitud: -75.5136,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Terraza con vista panorámica",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "180m2",
          Precio: "380000",
          Descripcion: "Amplia casa con diseño moderno en Manizales",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "3",
          Precio_Venta: "3200000",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "15",
          Direccion: "Popayán,Cauca",
          Latitud: 2.4447,
          Longitud: -76.6147,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Cerca de zonas verdes",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "120m2",
          Precio: "280000",
          Descripcion: "Casa encantadora en Popayán con jardín",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2400000",
          AgentId: "3",
          TypehousingId: "3",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "15",
          Direccion: "Popayán,Cauca",
          Latitud: 2.4447,
          Longitud: -76.6147,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Cerca de zonas verdes",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "120m2",
          Precio: "280000",
          Descripcion: "Casa encantadora en Popayán con jardín",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2400000",
          AgentId: "3",
          TypehousingId: "3",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "17",
          Direccion: "Bucaramanga,Santander",
          Latitud: 7.1198,
          Longitud: -73.1227,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Vista a la ciudad",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "110m2",
          Precio: "270000",
          Descripcion: "Apartamento moderno en el corazón de Bucaramanga",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2200000",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "18",
          Direccion: "Cali,Valle del Cauca",
          Latitud: 3.4516,
          Longitud: -76.532,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Patio amplio",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "150m2",
          Precio: "350000",
          Descripcion: "Casa con diseño contemporáneo en Cali",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "3",
          Precio_Venta: "3000000",
          AgentId: "3",
          TypehousingId: "3",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "18",
          Direccion: "Cali,Valle del Cauca",
          Latitud: 3.4516,
          Longitud: -76.532,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Patio amplio",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "150m2",
          Precio: "350000",
          Descripcion: "Casa con diseño contemporáneo en Cali",
          Imagen: JSON.stringify(
            {
              id: "prueba",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            },
            {
              id: "prueba02",
              url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
            }
          ),
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "3",
          Precio_Venta: "3000000",
          AgentId: "3",
          TypehousingId: "3",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
