"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Homes",
      [
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            "https://images.homify.com/image/upload/c_scale,h_282,w_500/v1437512726/p/photo/image/63599/10912_060DFR.jpg",
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            "https://images.homify.com/image/upload/c_scale,h_282,w_500/v1437512726/p/photo/image/63599/10912_060DFR.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "2",
          Direccion: "Manizales,Caldas",
          Latitud: 22.1,
          Longitud: 33.1,
          Cant_Cuartos: "2",
          Caracteristicas_Extra: "Tiene sauna",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "100m2",
          Precio: "20000",
          Descripcion:
            "Esta es un apartamento ubicado en una zona residencial de manizales",
          Imagen: [
            "https://media-cdn.tripadvisor.com/media/photo-s/0d/fa/42/d0/20161225-141245-largejpg.jpg",
            "https://media-cdn.tripadvisor.com/media/photo-s/0d/fa/42/d0/20161225-141245-largejpg.jpg",
            "https://media-cdn.tripadvisor.com/media/photo-s/0d/fa/42/d0/20161225-141245-largejpg.jpg",
          ],
          Tiene_Garaje_Moto: "si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "100.000.000",
          Estado:"Usado",
          Amueblado:"No",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "3",
          Direccion: "Bogotá, Cundinamarca",
          Latitud: 22.1,
          Longitud: 33.1,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene piscina",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "200m2",
          Precio: "5000000",
          Descripcion:
            "Esta es una casa ubicada en una zona exclusiva de Bogotá",
          Imagen: ["https://media-cdn.tripadvisor.com/media/photo-s/0d/fa/42/d0/20161225-141245-largejpg.jpg",
          "https://media-cdn.tripadvisor.com/media/photo-s/0d/fa/42/d0/20161225-141245-largejpg.jpg",
          "https://media-cdn.tripadvisor.com/media/photo-s/0d/fa/42/d0/20161225-141245-largejpg.jpg",
        ],
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "500000000",
          Estado:"Nuevo",
          Amueblado:"No",
          AgentId: "3",
          TypehousingId: "1",
          TypetargetId: "3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "4",
          Direccion: "Medellín, Antioquia",
          Latitud: 22.1,
          Longitud: 33.1,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Tiene vista panorámica",
          Tiene_Servicios_Incluidos: "Sí",
          Area_Inmueble: "150m2",
          Precio: "3500000",
          Descripcion:
            "Este es un apartamento moderno con una vista espectacular de la ciudad",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          // Imagen: JSON.stringify(
          //   {
          //     id: "prueba",
          //     url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          //   },
          //   {
          //     id: "prueba02",
          //     url: "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462884/vxo6dkiyzrdrcqiia1iz.jpg",
          //   }
          // ),
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Sí",
          Tiene_Patio: "No",
          Cant_Baños: "3",
          Precio_Venta: "700000000",
          Estado:"Construcción",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "2",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "2",
          Direccion: "Bogotá,Cundinamarca",
          Latitud: 4.6097,
          Longitud: -74.0817,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Piscina privada",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "150m2",
          Precio: "350000",
          Descripcion: "Amplia casa familiar en el corazón de Bogotá",
          Imagen: [
            "https://img10.naventcdn.com/avisos/18/00/66/70/80/35/720x532/366100635.jpg",
            "https://img10.naventcdn.com/avisos/18/00/66/70/80/35/720x532/366100635.jpg",
            "https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzNhMjdjMTg1LWZkYzAtNDczNy04ZDkzLWVkMjRhY2Q5ZjUwMi9hMzc4YzZmNy1kNzYzLTQ0YTctOGFjOS0xNDkzODQ0MmQ5M2YuanBnIiwiYnJhbmQiOiJSRVNFTSIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6ODQwLCJoZWlnaHQiOjYzMCwiZml0IjoiY292ZXIifX19",
            "https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzNhMjdjMTg1LWZkYzAtNDczNy04ZDkzLWVkMjRhY2Q5ZjUwMi9hMzc4YzZmNy1kNzYzLTQ0YTctOGFjOS0xNDkzODQ0MmQ5M2YuanBnIiwiYnJhbmQiOiJSRVNFTSIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6ODQwLCJoZWlnaHQiOjYzMCwiZml0IjoiY292ZXIifX19"
          ],
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "3",
          Precio_Venta: "5000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "3",
          Direccion: "Medellín,Antioquia",
          Latitud: 6.2447,
          Longitud: -75.5748,
          Cant_Cuartos: "2",
          Caracteristicas_Extra: "Vista panorámica a la montaña",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "80m2",
          Precio: "180000",
          Descripcion: "Apartamento acogedor con vista a la ciudad",
          Imagen: [
            "https://i.pinimg.com/564x/65/48/7d/65487d33ea38adf5f2bf7b181ff7cab0.jpg",
            "https://i.pinimg.com/736x/ef/d9/4f/efd94f368ebd078b4b0864db572d0141.jpg"
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "No",
          Cant_Baños: "1",
          Precio_Venta: "1500000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "3",
          TypehousingId: "1",
          TypetargetId: "3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "4",
          Direccion: "Cali,Valle del Cauca",
          Latitud: 3.4516,
          Longitud: -76.5320,
          Cant_Cuartos: "5",
          Caracteristicas_Extra: "Gimnasio y sauna",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "200m2",
          Precio: "500000",
          Descripcion: "Casa moderna con comodidades de lujo en Cali",
          Imagen: [
            "https://ventanasenaluminiotecnowindows.com/wp-content/uploads/2018/06/fachadas-de-las-casas-venezolanas.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "4",
          Precio_Venta: "8000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "3",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "5",
          Direccion: "Cartagena,Bolívar",
          Latitud: 10.3910,
          Longitud: -75.4794,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Cerca de la playa",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "120m2",
          Precio: "300000",
          Descripcion: "Casa de estilo colonial en el centro histórico de Cartagena",
          Imagen: [
            "https://19a40a38ba.cbaul-cdnwnd.com/cb628410adffd88428b32f51909ad715/200000040-436ab44632/7.jpg",
          ],
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2500000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "6",
          Direccion: "Pereira,Risaralda",
          Latitud: 4.8136,
          Longitud: -75.6961,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Jardín amplio",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "180m2",
          Precio: "400000",
          Descripcion: "Chalet elegante con vistas a las montañas en Pereira",
          Imagen: [
            "https://ventanasenaluminiotecnowindows.com/wp-content/uploads/2018/06/fachadas-de-las-casas-venezolanas.jpg",
            "https://ventanasenaluminiotecnowindows.com/wp-content/uploads/2018/06/fachadas-de-las-casas-venezolanas.jpg",

          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "3",
          Precio_Venta: "6000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "3",
          TypehousingId: "3",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "7",
          Direccion: "Barranquilla,Atlántico",
          Latitud: 10.9639,
          Longitud: -74.7967,
          Cant_Cuartos: "2",
          Caracteristicas_Extra: "Vista al mar",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "100m2",
          Precio: "250000",
          Descripcion: "Apartamento moderno con balcón en Barranquilla",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "1800000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "8",
          Direccion: "Santa Marta,Magdalena",
          Latitud: 11.2404,
          Longitud: -74.2115,
          Cant_Cuartos: "5",
          Caracteristicas_Extra: "Piscina comunitaria",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "200m2",
          Precio: "500000",
          Descripcion: "Casa de playa con acceso directo al mar en Santa Marta",
          Imagen: [
            "https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci9mMTQ1YTkzMy00OGQyLTNjYWEtOWQ4OC0zYjZlMGJjZWZhY2EvNjk1ZDQ4NjdlM2ZiZDBlNTU5NDdmMTNhZjJlODZkNGVkYjBkZjM4YWQ2YzlmMDY3NjQ2ZGU0NDZlNmExYTNhYS5qcGciLCJicmFuZCI6IlJFU0VNIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo4NDAsImhlaWdodCI6NjMwLCJmaXQiOiJjb3ZlciJ9fX0=",
          ],
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "4",
          Precio_Venta: "7000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "9",
          Direccion: "Villavicencio,Meta",
          Latitud: 4.1420,
          Longitud: -73.6266,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Cerca de parques naturales",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "120m2",
          Precio: "280000",
          Descripcion: "Casa acogedora con jardín en Villavicencio",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2400000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "3",
          TypehousingId: "3",
          TypetargetId: "3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "10",
          Direccion: "Cúcuta,Norte de Santander",
          Latitud: 7.8947,
          Longitud: -72.4960,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Zona tranquila",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "150m2",
          Precio: "380000",
          Descripcion: "Amplia casa familiar en Cúcuta",
          Imagen: [
            "https://http2.mlstatic.com/D_NQ_NP_602909-MLM51541072792_092022-O.webp",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "No",
          Cant_Baños: "3",
          Precio_Venta: "3000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "10",
          Direccion: "Cúcuta,Norte de Santander",
          Latitud: 7.8947,
          Longitud: -72.4960,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Zona tranquila",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "150m2",
          Precio: "380000",
          Descripcion: "Amplia casa familiar en Cúcuta",
          Imagen: [
            "https://http2.mlstatic.com/D_NQ_NP_992548-MLM54765932784_032023-O.webp",
            "https://http2.mlstatic.com/D_NQ_NP_847151-MLM69762680210_062023-O.webp",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "No",
          Cant_Baños: "3",
          Precio_Venta: "3000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "11",
          Direccion: "Pasto,Nariño",
          Latitud: 1.2136,
          Longitud: -77.2811,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Vista a la montaña",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "110m2",
          Precio: "250000",
          Descripcion: "Apartamento con encanto en el centro de Pasto",
          Imagen: [
            "https://http2.mlstatic.com/D_NQ_NP_956782-MLM53569972155_022023-O.webp",
            "https://http2.mlstatic.com/D_NQ_NP_897659-MLM70493737110_072023-O.webp",
            "https://http2.mlstatic.com/D_NQ_NP_914140-MLA70099891147_062023-O.webp"
          ],
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "11",
          Direccion: "Pasto,Nariño",
          Latitud: 1.2136,
          Longitud: -77.2811,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Vista a la montaña",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "110m2",
          Precio: "250000",
          Descripcion: "Apartamento con encanto en el centro de Pasto",
          Imagen: [
            "https://i.pinimg.com/736x/9b/7b/76/9b7b76f2814d13ec6dcc96ec13c2ad73.jpg",
          ],
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "13",
          Direccion: "Armenia,Quindío",
          Latitud: 4.5341,
          Longitud: -75.6759,
          Cant_Cuartos: "2",
          Caracteristicas_Extra: "Casa de diseño contemporáneo",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "90m2",
          Precio: "200000",
          Descripcion: "Acogedora casa en el corazón de Armenia",
          Imagen: [
            "https://i.pinimg.com/736x/9b/7b/76/9b7b76f2814d13ec6dcc96ec13c2ad73.jpg",
            "https://i.pinimg.com/736x/9b/7b/76/9b7b76f2814d13ec6dcc96ec13c2ad73.jpg",
          ],
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "1",
          Precio_Venta: "1800000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "2",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "14",
          Direccion: "Manizales,Caldas",
          Latitud: 5.0586,
          Longitud: -75.5136,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Terraza con vista panorámica",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "180m2",
          Precio: "380000",
          Descripcion: "Amplia casa con diseño moderno en Manizales",
          Imagen: [
            "https://i.pinimg.com/736x/fe/ef/32/feef32dde22a87db492bdd7b4f063d58.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "3",
          Precio_Venta: "3200000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "15",
          Direccion: "Popayán,Cauca",
          Latitud: 2.4447,
          Longitud: -76.6147,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Cerca de zonas verdes",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "120m2",
          Precio: "280000",
          Descripcion: "Casa encantadora en Popayán con jardín",
          Imagen: [
            "https://i.pinimg.com/736x/fe/ef/32/feef32dde22a87db492bdd7b4f063d58.jpg",
            "https://i.pinimg.com/originals/bd/a6/8d/bda68d25d2e28c995d048f6426a590ac.jpg"
          ],
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2400000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "3",
          TypehousingId: "3",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "15",
          Direccion: "Popayán,Cauca",
          Latitud: 2.4447,
          Longitud: -76.6147,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Cerca de zonas verdes",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "120m2",
          Precio: "280000",
          Descripcion: "Casa encantadora en Popayán con jardín",
          Imagen: [
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsQwcbuzt1MQMwqCytx0356mQ9sbQ_CoN9uw&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXMF3IY652dRrhvvIIkEw82A7gC3h-PPOqe7g4s03tHMhX6tuFCyFnOTpHdmotDTy9qBs&usqp=CAU"
          ],
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2400000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "3",
          TypehousingId: "3",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "17",
          Direccion: "Bucaramanga,Santander",
          Latitud: 7.1198,
          Longitud: -73.1227,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Vista a la ciudad",
          Tiene_Servicios_Incluidos: "No",
          Area_Inmueble: "110m2",
          Precio: "270000",
          Descripcion: "Apartamento moderno en el corazón de Bucaramanga",
          Imagen: [
            "https://i.blogs.es/7e9aa6/bluelick/450_1000.webp",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkhaenMRxrGs2cxW5vjBXB_LvoyNr7jeei5bEoHhxR3EbGbzwImdaocqMphTRfuw6hutQ&usqp=CAU"
          ],
          Tiene_Garaje_Moto: "No",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "Si",
          Cant_Baños: "2",
          Precio_Venta: "2200000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "2",
          TypehousingId: "2",
          TypetargetId: "3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "18",
          Direccion: "Cali,Valle del Cauca",
          Latitud: 3.4516,
          Longitud: -76.5320,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Patio amplio",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "150m2",
          Precio: "350000",
          Descripcion: "Casa con diseño contemporáneo en Cali",
          Imagen: [
            "https://chile.slideprop.com/photo-venta-casa-quinta-normal-idphoto-1500696.jpg",
            "https://chile.slideprop.com/photo-venta-casa-quinta-normal-idphoto-1500696.jpg",
            "https://chile.slideprop.com/photo-venta-casa-quinta-normal-idphoto-1500696.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "3",
          Precio_Venta: "3000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "3",
          TypehousingId: "3",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "18",
          Direccion: "Cali,Valle del Cauca",
          Latitud: 3.4516,
          Longitud: -76.5320,
          Cant_Cuartos: "4",
          Caracteristicas_Extra: "Patio amplio",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "150m2",
          Precio: "350000",
          Descripcion: "Casa con diseño contemporáneo en Cali",
          Imagen: [
            "",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "No",
          Tiene_Patio: "Si",
          Cant_Baños: "3",
          Precio_Venta: "3000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "3",
          TypehousingId: "3",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        ////////////////////////////////
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Construcción",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3lvxsYk7gcXhqFLniiI7kwzTIaOBB3Dwaaw&usqp=CAU",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Construcción",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Construcción",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Construcción",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://i.pinimg.com/236x/9f/76/98/9f7698cfc72c53ef2ec6e25a4a237499.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Construcción",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://i.pinimg.com/236x/9f/76/98/9f7698cfc72c53ef2ec6e25a4a237499.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://i.pinimg.com/236x/91/27/fe/9127feb957b31779770ebaf66f8beb2b.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"Si",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Usado",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Usado",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Usado",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Usado",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },{
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Usado",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },{
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Usado",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },{
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Usado",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },{
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Usado",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },{
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Usado",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },{
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Usado",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },{
          Codigo_Vivienda: "1",
          Direccion: "Manizales,Caldas",
          Latitud: 5.067,
          Longitud: -75.517,
          Cant_Cuartos: "3",
          Caracteristicas_Extra: "Tiene cancha de futbol",
          Tiene_Servicios_Incluidos: "Si",
          Area_Inmueble: "10m2",
          Precio: "20000",
          Descripcion:
            "Esta es una casa de campo ubicada en una zona residencial de manizales",
          Imagen: [
            "https://res.cloudinary.com/dxnsmwmgv/image/upload/v1699462882/fdwry9u349mfjjl4bnvd.jpg",
          ],
          Tiene_Garaje_Moto: "Si",
          Tiene_Garaje_Carro: "Si",
          Tiene_Patio: "No",
          Cant_Baños: "2",
          Precio_Venta: "2000000",
          Estado:"Nuevo",
          Amueblado:"No",
          AgentId: "1",
          TypehousingId: "1",
          TypetargetId: "1",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
